import type { AMCPlan } from '@/types/amc';

export const AMC_PLANS: AMCPlan[] = [
  {
    id: 'amc-basic',
    name: 'Basic',
    tagline: 'Essential Protection',
    price: 1499,
    pricePerUnit: true,
    billingCycle: 'annual',
    description: 'Essential maintenance for worry-free AC performance throughout the year.',
    color: 'blue',
    popular: false,
    features: [
      { label: 'Scheduled Services', value: '2 per year', included: true },
      { label: 'Cleaning & Inspection', value: 'Each visit', included: true },
      { label: 'Performance Report', value: 'Digital', included: true },
      { label: 'Labour Charges', value: 'Discounted 20%', included: true },
      { label: 'Spare Parts Discount', value: '10%', included: true },
      { label: 'Emergency Service', value: 'Standard', included: true },
      { label: 'Priority Response', value: false, included: false },
      { label: 'Gas Refilling', value: false, included: false },
      { label: 'PCB Coverage', value: false, included: false },
    ],
    cta: 'Get Basic Plan',
    highlights: ['₹1,499/unit/year', '2 services included', '20% off labour'],
  },
  {
    id: 'amc-standard',
    name: 'Standard',
    tagline: 'Best Value — Most Popular',
    price: 2499,
    pricePerUnit: true,
    billingCycle: 'annual',
    description: 'Comprehensive coverage with priority service for maximum peace of mind.',
    color: 'primary',
    popular: true,
    features: [
      { label: 'Scheduled Services', value: '3 per year', included: true },
      { label: 'Cleaning & Inspection', value: 'Each visit', included: true },
      { label: 'Performance Report', value: 'Digital', included: true },
      { label: 'Labour Charges', value: 'Free on covered repairs', included: true },
      { label: 'Spare Parts Discount', value: '20%', included: true },
      { label: 'Emergency Service', value: '< 4 Hours', included: true },
      { label: 'Priority Response', value: '24/7', included: true },
      { label: 'Gas Refilling', value: '1 per year', included: true },
      { label: 'PCB Coverage', value: false, included: false },
    ],
    cta: 'Get Standard Plan',
    highlights: ['₹2,499/unit/year', '3 services included', 'Free labour', '1 gas fill included'],
  },
  {
    id: 'amc-premium',
    name: 'Premium',
    tagline: 'Total Protection',
    price: 3999,
    pricePerUnit: true,
    billingCycle: 'annual',
    description: 'All-inclusive premium plan with complete coverage for zero-worry AC ownership.',
    color: 'gold',
    popular: false,
    features: [
      { label: 'Scheduled Services', value: '4 per year', included: true },
      { label: 'Cleaning & Inspection', value: 'Each visit', included: true },
      { label: 'Performance Report', value: 'Detailed Digital', included: true },
      { label: 'Labour Charges', value: 'Fully Covered', included: true },
      { label: 'Spare Parts Discount', value: '30%', included: true },
      { label: 'Emergency Service', value: '< 2 Hours', included: true },
      { label: 'Priority Response', value: '24/7 Hotline', included: true },
      { label: 'Gas Refilling', value: 'Unlimited', included: true },
      { label: 'PCB Coverage', value: 'Up to ₹2,000', included: true },
    ],
    cta: 'Get Premium Plan',
    highlights: ['₹3,999/unit/year', '4 services included', 'Fully covered', 'PCB protection'],
  },
  {
    id: 'amc-commercial',
    name: 'Commercial',
    tagline: 'For Businesses & Buildings',
    price: 0, // Custom pricing
    pricePerUnit: false,
    billingCycle: 'annual',
    description: 'Custom-designed maintenance contracts for offices, hospitals, schools, and commercial buildings.',
    color: 'slate',
    popular: false,
    features: [
      { label: 'Scheduled Services', value: 'Custom', included: true },
      { label: 'Multi-unit Coverage', value: '5+ units', included: true },
      { label: 'Dedicated Technician', value: 'Assigned', included: true },
      { label: 'Labour Charges', value: 'Fully Covered', included: true },
      { label: 'Spare Parts Discount', value: '35%', included: true },
      { label: 'Emergency Service', value: '< 2 Hours', included: true },
      { label: 'SLA Agreement', value: 'Customized', included: true },
      { label: 'Monthly Reports', value: 'Detailed', included: true },
      { label: 'Energy Audit', value: 'Annual', included: true },
    ],
    cta: 'Request Custom Quote',
    highlights: ['Custom pricing', 'Dedicated technician', 'SLA guaranteed', 'Energy audit included'],
  },
];
