export interface AreaLocation {
  id: string;
  slug: string;
  name: string;
  zone: string;
  postalCode: string;
  responseTime: string;
  metaTitle: string;
  metaDescription: string;
  heading: string;
  intro: string;
  nearbyHubs: string[];
  localFaqs: { question: string; answer: string }[];
}

export const AREA_LOCATIONS: AreaLocation[] = [
  {
    id: 'perungalathur',
    slug: 'ac-service-perungalathur',
    name: 'Perungalathur',
    zone: 'South Chennai Base',
    postalCode: '600063',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Perungalathur | AC Repair & Cleaning | ChillFix',
    metaDescription: 'ChillFix AC Service provides expert AC servicing, repair, foam jet wash cleaning, gas filling and installation in Perungalathur, Chennai.',
    heading: 'AC Service & Repair in Perungalathur',
    intro: 'ChillFix AC Service is based in Perungalathur, providing prompt doorstep AC servicing, repair, chemical jet wash cleaning, gas leak diagnosis, and Split/Window AC installation across New Perungalathur, Old Perungalathur, Peerkankaranai, and Kamaraj Nagar.',
    nearbyHubs: ['New Perungalathur', 'Old Perungalathur', 'Peerkankaranai', 'Kamaraj Nagar', 'Nedungundram', 'Srinivasa Nagar'],
    localFaqs: [
      { question: 'Do you provide local AC service in Perungalathur?', answer: 'Yes! ChillFix AC Service is based in Perungalathur, providing fast local technician visits across New Perungalathur, Old Perungalathur, and Peerkankaranai.' },
      { question: 'What AC services do you offer in Perungalathur?', answer: 'We provide general AC servicing, foam jet-wash deep cleaning, cooling repair, gas leak diagnosis & refilling, PCB repair, and Split/Window AC installation.' },
    ],
  },
  {
    id: 'tambaram',
    slug: 'ac-service-tambaram',
    name: 'Tambaram',
    zone: 'South Chennai',
    postalCode: '600045',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Tambaram | AC Repair & Cleaning | ChillFix',
    metaDescription: 'ChillFix provides reliable AC service in Tambaram, Chennai. Split & Window AC repair, foam jet wash cleaning, gas filling & installation.',
    heading: 'AC Service & Repair in Tambaram',
    intro: 'ChillFix AC Service provides professional AC repair and servicing across Tambaram East, Tambaram West, Tambaram Sanatorium, Selaiyur, and Camp Road. We fix cooling issues, water leaks, gas leaks, and circuit board problems.',
    nearbyHubs: ['Tambaram East', 'Tambaram West', 'Tambaram Sanatorium', 'Selaiyur', 'Camp Road', 'Padmavathi Nagar'],
    localFaqs: [
      { question: 'How fast can an AC technician reach Tambaram?', answer: 'Our mobile service team covers Tambaram East and West daily, providing prompt doorstep service.' },
      { question: 'Do you service Split and Window ACs in Tambaram?', answer: 'Yes! We service all Split, Window, Inverter, and Cassette AC models across Tambaram.' },
    ],
  },
  {
    id: 'vandalur',
    slug: 'ac-service-vandalur',
    name: 'Vandalur',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Vandalur | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Expert AC service in Vandalur, Chennai. Split & Window AC repair, jet wash cleaning, gas filling & installation near Zoo & Crescent College.',
    heading: 'AC Service & Repair in Vandalur',
    intro: 'ChillFix AC Service offers reliable AC servicing and breakdown repairs in Vandalur, Otteri, Urapakkam, and Crescent College Road. Fast local response for residential homes and commercial units.',
    nearbyHubs: ['Vandalur Junction', 'Otteri', 'Urapakkam', 'Crescent Zone', 'GST Road Vandalur'],
    localFaqs: [
      { question: 'Do you cover Urapakkam and Vandalur area?', answer: 'Yes! Our Perungalathur local base easily serves Vandalur, Otteri, and Urapakkam.' },
    ],
  },
  {
    id: 'manivakkam',
    slug: 'ac-service-manivakkam',
    name: 'Manivakkam',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Manivakkam | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Doorstep AC service in Manivakkam, Chennai. Split AC repair, jet wash cleaning, gas refilling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Manivakkam',
    intro: 'ChillFix AC Service delivers complete AC repair, servicing, and installation across Manivakkam, Karasangal, and Mudichur Road. Upfront pricing and written service warranty.',
    nearbyHubs: ['Manivakkam Junction', 'Karasangal', 'Mudichur Road', 'Krishna Nagar', 'Natesan Nagar'],
    localFaqs: [
      { question: 'Do you provide same-day AC service in Manivakkam?', answer: 'Yes! We provide same-day technician visits across Manivakkam and surrounding colonies.' },
    ],
  },
  {
    id: 'chromepet',
    slug: 'ac-service-chromepet',
    name: 'Chromepet',
    zone: 'South Chennai',
    postalCode: '600044',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Chromepet | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Professional AC service in Chromepet, Chennai. AC repair, jet wash cleaning, gas refilling & installation near Radha Nagar & MIT Campus.',
    heading: 'AC Service & Repair in Chromepet',
    intro: 'ChillFix AC Service provides professional AC repair and maintenance in Chromepet, Radha Nagar, Hasthinapuram, and MIT Campus zone. We diagnose cooling problems on-site with genuine spare parts.',
    nearbyHubs: ['Radha Nagar', 'Hasthinapuram', 'MIT Campus Road', 'Nemilichery', 'CLRI Nagar'],
    localFaqs: [
      { question: 'What is the diagnostic fee for AC repair in Chromepet?', answer: 'Diagnostic fee is ₹349, which is 100% adjusted into your final bill when proceeding with repair.' },
    ],
  },
  {
    id: 'pallavaram',
    slug: 'ac-service-pallavaram',
    name: 'Pallavaram',
    zone: 'South Chennai',
    postalCode: '600043',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Pallavaram | Doorstep AC Repair & Cleaning',
    metaDescription: 'Trusted AC service in Pallavaram, Chennai. Split & Window AC repair, foam jet wash, gas filling & AMC near Zamin Pallavaram & Pammal.',
    heading: 'AC Service & Repair in Pallavaram',
    intro: 'ChillFix AC Service provides complete AC repair, jet wash cleaning, gas leak detection, and new AC installation across Zamin Pallavaram, Old Pallavaram, and Cantonment area.',
    nearbyHubs: ['Zamin Pallavaram', 'Old Pallavaram', 'Keelkattalai', 'Pammal', 'Cantonment Area'],
    localFaqs: [
      { question: 'Do you service ACs in Pammal near Pallavaram?', answer: 'Yes! We cover Pammal, Keelkattalai, and Zamin Pallavaram.' },
    ],
  },
  {
    id: 'mudichur',
    slug: 'ac-service-mudichur',
    name: 'Mudichur',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Mudichur | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Fast AC service in Mudichur, Chennai. Split AC repair, jet wash cleaning, gas filling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Mudichur',
    intro: 'ChillFix AC Service provides fast doorstep AC servicing, jet wash cleaning, and repair across Mudichur, Laxmi Nagar, and Varadarajapuram.',
    nearbyHubs: ['Mudichur Junction', 'Laxmi Nagar', 'Varadarajapuram', 'Attai Kulam'],
    localFaqs: [
      { question: 'Do you provide AC jet wash cleaning in Mudichur?', answer: 'Yes! High-pressure foam jet wash is available for all Split and Window ACs in Mudichur.' },
    ],
  },
  {
    id: 'selaiyur',
    slug: 'ac-service-selaiyur',
    name: 'Selaiyur',
    zone: 'South Chennai',
    postalCode: '600073',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Selaiyur | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Certified AC service in Selaiyur, Chennai. Split & Window AC repair, jet wash cleaning, gas filling near Camp Road & Bharat University.',
    heading: 'AC Service & Repair in Selaiyur',
    intro: 'ChillFix AC Service provides professional AC servicing, breakdown repair, and gas refilling across Selaiyur, Camp Road, Agaram Main Road, and Mahalakshmi Nagar.',
    nearbyHubs: ['Camp Road', 'Agaram Main Road', 'Mahalakshmi Nagar', 'Bharat University Zone'],
    localFaqs: [
      { question: 'Do you service inverter ACs in Selaiyur?', answer: 'Yes! We specialize in Dual Inverter AC circuit boards, gas filling, and coil cleaning.' },
    ],
  },
  {
    id: 'chitlapakkam',
    slug: 'ac-service-chitlapakkam',
    name: 'Chitlapakkam',
    zone: 'South Chennai',
    postalCode: '600064',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Chitlapakkam | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Reliable AC service in Chitlapakkam, Chennai. Split AC repair, foam jet wash, gas refilling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Chitlapakkam',
    intro: 'ChillFix AC Service offers reliable AC maintenance and breakdown repairs across Chitlapakkam, Sanatorium, and Rajakilpakkam.',
    nearbyHubs: ['Chitlapakkam Main Road', 'Rajakilpakkam', 'Sanatorium Zone', 'Babu Street'],
    localFaqs: [
      { question: 'How do I book AC service in Chitlapakkam?', answer: 'Call +91 90804 95932 or chat on WhatsApp for fast technician booking.' },
    ],
  },
  {
    id: 'pammal',
    slug: 'ac-service-pammal',
    name: 'Pammal',
    zone: 'South Chennai',
    postalCode: '600075',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Pammal | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Doorstep AC service in Pammal, Chennai. Split & Window AC repair, jet wash cleaning, gas filling & installation.',
    heading: 'AC Service & Repair in Pammal',
    intro: 'ChillFix AC Service provides doorstep AC servicing and repair in Pammal, Pozhichalur, and Nagalkeni with upfront pricing.',
    nearbyHubs: ['Pammal Main Road', 'Pozhichalur', 'Nagalkeni', 'Anna Nagar Pammal'],
    localFaqs: [
      { question: 'Do you service commercial units in Pammal?', answer: 'Yes! We service residential and commercial AC units in Pammal.' },
    ],
  },
  {
    id: 'medavakkam',
    slug: 'ac-service-medavakkam',
    name: 'Medavakkam',
    zone: 'South Chennai',
    postalCode: '600100',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Medavakkam | AC Repair & Cleaning | ChillFix',
    metaDescription: 'Expert AC service in Medavakkam, Chennai. Split & Window AC repair, foam jet wash, gas filling & installation.',
    heading: 'AC Service & Repair in Medavakkam',
    intro: 'ChillFix AC Service offers complete AC servicing, jet wash cleaning, and gas refilling across Medavakkam, Perumbakkam, and Kovilambakkam.',
    nearbyHubs: ['Medavakkam Junction', 'Perumbakkam', 'Kovilambakkam', 'Babu Nagar Medavakkam'],
    localFaqs: [
      { question: 'Do you offer AC installation in Medavakkam?', answer: 'Yes! Same-day Split and Window AC installation is available.' },
    ],
  },
  {
    id: 'sholinganallur',
    slug: 'ac-service-sholinganallur',
    name: 'Sholinganallur',
    zone: 'OMR IT Corridor',
    postalCode: '600119',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Sholinganallur | OMR AC Repair & Jet Wash | ChillFix',
    metaDescription: 'Fast AC service in Sholinganallur, OMR Chennai. AC repair, jet wash, gas refilling & installation for apartments & IT parks.',
    heading: 'AC Service & Repair in Sholinganallur',
    intro: 'ChillFix AC Service provides prompt AC servicing and breakdown repairs in Sholinganallur and along the OMR IT Corridor.',
    nearbyHubs: ['Elcot SEZ Zone', 'Sholinganallur Junction', 'Semmancheri', 'Perumbakkam'],
    localFaqs: [
      { question: 'Are weekend AC bookings available in Sholinganallur?', answer: 'Yes! We are open Saturdays and Sundays.' },
    ],
  },
  {
    id: 'omr',
    slug: 'ac-service-omr',
    name: 'OMR (Old Mahabalipuram Road)',
    zone: 'OMR IT Corridor',
    postalCode: '600096',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in OMR | OMR AC Repair & Maintenance | ChillFix',
    metaDescription: 'AC service across OMR Chennai (Perungudi to Navalur). Fast technician response for Split AC repair, jet wash & AMC.',
    heading: 'AC Service & Repair Across OMR',
    intro: 'ChillFix AC Service covers the OMR stretch from Perungudi to Thoraipakkam, Sholinganallur, and Navalur.',
    nearbyHubs: ['Perungudi', 'Thoraipakkam', 'Kandanchavadi', 'Navalur', 'Siruseri'],
    localFaqs: [
      { question: 'Which areas along OMR do you cover?', answer: 'We cover all areas along OMR including Perungudi, Thoraipakkam, Sholinganallur, and Navalur.' },
    ],
  },
];
