export interface AreaLocation {
  id: string;
  slug: string;
  name: string;
  zone: string;
  postalCode: string;
  responseTime: string;
  metaTitle: string;
  metaDescription: string;
  heading: string;
  intro: string;
  nearbyHubs: string[];
  localFaqs: { question: string; answer: string }[];
}

export const AREA_LOCATIONS: AreaLocation[] = [
  {
    id: 'perungalathur',
    slug: 'perungalathur',
    name: 'Perungalathur',
    zone: 'South Chennai Base',
    postalCode: '600063',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Perungalathur | ChillFix AC Service',
    metaDescription: 'ChillFix AC Service is based in Perungalathur, providing prompt AC servicing, repair, foam jet wash cleaning, gas filling and installation.',
    heading: 'AC Service & Repair in Perungalathur',
    intro: 'ChillFix AC Service is headquartered in Perungalathur, providing doorstep AC servicing, breakdown repair, chemical jet wash cleaning, gas leak diagnosis, and Split/Window AC installation across New Perungalathur, Old Perungalathur, Peerkankaranai, and Kamaraj Nagar.',
    nearbyHubs: ['New Perungalathur', 'Old Perungalathur', 'Peerkankaranai', 'Kamaraj Nagar', 'Nedungundram', 'Srinivasa Nagar'],
    localFaqs: [
      { question: 'Do you provide local AC service in Perungalathur?', answer: 'Yes! ChillFix AC Service is based in Perungalathur, providing fast local technician visits across New Perungalathur, Old Perungalathur, and Peerkankaranai.' },
      { question: 'What AC services do you offer in Perungalathur?', answer: 'We provide general AC servicing, foam jet-wash deep cleaning, cooling repair, gas leak diagnosis & refilling, PCB repair, and Split/Window AC installation.' },
    ],
  },
  {
    id: 'tambaram',
    slug: 'tambaram',
    name: 'Tambaram',
    zone: 'South Chennai',
    postalCode: '600045',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Tambaram | ChillFix AC Service',
    metaDescription: 'ChillFix provides reliable AC service in Tambaram, Chennai. Split & Window AC repair, foam jet wash cleaning, gas filling & installation.',
    heading: 'AC Service & Repair in Tambaram',
    intro: 'ChillFix AC Service provides professional AC repair and servicing across Tambaram East, Tambaram West, Tambaram Sanatorium, Selaiyur, and Camp Road. We fix cooling issues, water leaks, gas leaks, and circuit board problems.',
    nearbyHubs: ['Tambaram East', 'Tambaram West', 'Tambaram Sanatorium', 'Selaiyur', 'Camp Road', 'Padmavathi Nagar'],
    localFaqs: [
      { question: 'How fast can an AC technician reach Tambaram?', answer: 'Our mobile service team covers Tambaram East and West daily, providing prompt doorstep service.' },
      { question: 'Do you service Split and Window ACs in Tambaram?', answer: 'Yes! We service all Split, Window, Inverter, and Cassette AC models across Tambaram.' },
    ],
  },
  {
    id: 'chromepet',
    slug: 'chromepet',
    name: 'Chromepet',
    zone: 'South Chennai',
    postalCode: '600044',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Chromepet | ChillFix AC Service',
    metaDescription: 'Professional AC service in Chromepet, Chennai. AC repair, jet wash cleaning, gas refilling & installation near Radha Nagar & MIT Campus.',
    heading: 'AC Service & Repair in Chromepet',
    intro: 'ChillFix AC Service provides professional AC repair and maintenance in Chromepet, Radha Nagar, Hasthinapuram, and MIT Campus zone. We diagnose cooling problems on-site with genuine spare parts.',
    nearbyHubs: ['Radha Nagar', 'Hasthinapuram', 'MIT Campus Road', 'Nemilichery', 'CLRI Nagar'],
    localFaqs: [
      { question: 'What is the diagnostic fee for AC repair in Chromepet?', answer: 'Diagnostic fee is ₹349, which is 100% adjusted into your final bill when proceeding with repair.' },
    ],
  },
  {
    id: 'pallavaram',
    slug: 'pallavaram',
    name: 'Pallavaram',
    zone: 'South Chennai',
    postalCode: '600043',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Pallavaram | ChillFix AC Service',
    metaDescription: 'Trusted AC service in Pallavaram, Chennai. Split & Window AC repair, foam jet wash, gas filling & AMC near Zamin Pallavaram & Pammal.',
    heading: 'AC Service & Repair in Pallavaram',
    intro: 'ChillFix AC Service provides complete AC repair, jet wash cleaning, gas leak detection, and new AC installation across Zamin Pallavaram, Old Pallavaram, and Cantonment area.',
    nearbyHubs: ['Zamin Pallavaram', 'Old Pallavaram', 'Keelkattalai', 'Pammal', 'Cantonment Area'],
    localFaqs: [
      { question: 'Do you service ACs in Pammal near Pallavaram?', answer: 'Yes! We cover Pammal, Keelkattalai, and Zamin Pallavaram.' },
    ],
  },
  {
    id: 'vandalur',
    slug: 'vandalur',
    name: 'Vandalur',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Vandalur | ChillFix AC Service',
    metaDescription: 'Expert AC service in Vandalur, Chennai. Split & Window AC repair, jet wash cleaning, gas filling & installation near Zoo & Crescent College.',
    heading: 'AC Service & Repair in Vandalur',
    intro: 'ChillFix AC Service offers reliable AC servicing and breakdown repairs in Vandalur, Otteri, Urapakkam, and Crescent College Road. Fast local response for residential homes and commercial units.',
    nearbyHubs: ['Vandalur Junction', 'Otteri', 'Urapakkam', 'Crescent Zone', 'GST Road Vandalur'],
    localFaqs: [
      { question: 'Do you cover Urapakkam and Vandalur area?', answer: 'Yes! Our Perungalathur local base easily serves Vandalur, Otteri, and Urapakkam.' },
    ],
  },
  {
    id: 'manivakkam',
    slug: 'manivakkam',
    name: 'Manivakkam',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Manivakkam | ChillFix AC Service',
    metaDescription: 'Doorstep AC service in Manivakkam, Chennai. Split AC repair, jet wash cleaning, gas refilling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Manivakkam',
    intro: 'ChillFix AC Service delivers complete AC repair, servicing, and installation across Manivakkam, Karasangal, and Mudichur Road. Upfront pricing and written service warranty.',
    nearbyHubs: ['Manivakkam Junction', 'Karasangal', 'Mudichur Road', 'Krishna Nagar', 'Natesan Nagar'],
    localFaqs: [
      { question: 'Do you provide same-day AC service in Manivakkam?', answer: 'Yes! We provide same-day technician visits across Manivakkam and surrounding colonies.' },
    ],
  },
  {
    id: 'mudichur',
    slug: 'mudichur',
    name: 'Mudichur',
    zone: 'South Chennai',
    postalCode: '600048',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Mudichur | ChillFix AC Service',
    metaDescription: 'Fast AC service in Mudichur, Chennai. Split AC repair, jet wash cleaning, gas filling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Mudichur',
    intro: 'ChillFix AC Service provides fast doorstep AC servicing, jet wash cleaning, and repair across Mudichur, Laxmi Nagar, and Varadarajapuram.',
    nearbyHubs: ['Mudichur Junction', 'Laxmi Nagar', 'Varadarajapuram', 'Attai Kulam'],
    localFaqs: [
      { question: 'Do you provide AC jet wash cleaning in Mudichur?', answer: 'Yes! High-pressure foam jet wash is available for all Split and Window ACs in Mudichur.' },
    ],
  },
  {
    id: 'selaiyur',
    slug: 'selaiyur',
    name: 'Selaiyur',
    zone: 'South Chennai',
    postalCode: '600073',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Selaiyur | ChillFix AC Service',
    metaDescription: 'Certified AC service in Selaiyur, Chennai. Split & Window AC repair, jet wash cleaning, gas filling near Camp Road & Bharat University.',
    heading: 'AC Service & Repair in Selaiyur',
    intro: 'ChillFix AC Service provides professional AC servicing, breakdown repair, and gas refilling across Selaiyur, Camp Road, Agaram Main Road, and Mahalakshmi Nagar.',
    nearbyHubs: ['Camp Road', 'Agaram Main Road', 'Mahalakshmi Nagar', 'Bharat University Zone'],
    localFaqs: [
      { question: 'Do you service inverter ACs in Selaiyur?', answer: 'Yes! We specialize in Dual Inverter AC circuit boards, gas filling, and coil cleaning.' },
    ],
  },
  {
    id: 'chitlapakkam',
    slug: 'chitlapakkam',
    name: 'Chitlapakkam',
    zone: 'South Chennai',
    postalCode: '600064',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Chitlapakkam | ChillFix AC Service',
    metaDescription: 'Reliable AC service in Chitlapakkam, Chennai. Split AC repair, foam jet wash, gas refilling & installation by ChillFix AC Service.',
    heading: 'AC Service & Repair in Chitlapakkam',
    intro: 'ChillFix AC Service offers reliable AC maintenance and breakdown repairs across Chitlapakkam, Sanatorium, and Rajakilpakkam.',
    nearbyHubs: ['Chitlapakkam Main Road', 'Rajakilpakkam', 'Sanatorium Zone', 'Babu Street'],
    localFaqs: [
      { question: 'How do I book AC service in Chitlapakkam?', answer: 'Call +91 90804 95932 or chat on WhatsApp for fast technician booking.' },
    ],
  },
  {
    id: 'pammal',
    slug: 'pammal',
    name: 'Pammal',
    zone: 'South Chennai',
    postalCode: '600075',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Pammal | ChillFix AC Service',
    metaDescription: 'Doorstep AC service in Pammal, Chennai. Split & Window AC repair, jet wash cleaning, gas filling & installation.',
    heading: 'AC Service & Repair in Pammal',
    intro: 'ChillFix AC Service provides doorstep AC servicing and repair in Pammal, Pozhichalur, and Nagalkeni with upfront pricing.',
    nearbyHubs: ['Pammal Main Road', 'Pozhichalur', 'Nagalkeni', 'Anna Nagar Pammal'],
    localFaqs: [
      { question: 'Do you service commercial units in Pammal?', answer: 'Yes! We service residential and commercial AC units in Pammal.' },
    ],
  },
  {
    id: 'medavakkam',
    slug: 'medavakkam',
    name: 'Medavakkam',
    zone: 'South Chennai',
    postalCode: '600100',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Medavakkam | ChillFix AC Service',
    metaDescription: 'Expert AC service in Medavakkam, Chennai. Split & Window AC repair, foam jet wash, gas filling & installation.',
    heading: 'AC Service & Repair in Medavakkam',
    intro: 'ChillFix AC Service offers complete AC servicing, jet wash cleaning, and gas refilling across Medavakkam, Perumbakkam, and Kovilambakkam.',
    nearbyHubs: ['Medavakkam Junction', 'Perumbakkam', 'Kovilambakkam', 'Babu Nagar Medavakkam'],
    localFaqs: [
      { question: 'Do you offer AC installation in Medavakkam?', answer: 'Yes! Same-day Split and Window AC installation is available.' },
    ],
  },
  {
    id: 'sholinganallur',
    slug: 'sholinganallur',
    name: 'Sholinganallur',
    zone: 'OMR IT Corridor',
    postalCode: '600119',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Sholinganallur | ChillFix AC Service',
    metaDescription: 'Fast AC service in Sholinganallur, OMR Chennai. AC repair, jet wash, gas refilling & installation for apartments & IT parks.',
    heading: 'AC Service & Repair in Sholinganallur',
    intro: 'ChillFix AC Service provides prompt AC servicing and breakdown repairs in Sholinganallur and along the OMR IT Corridor.',
    nearbyHubs: ['Elcot SEZ Zone', 'Sholinganallur Junction', 'Semmancheri', 'Perumbakkam'],
    localFaqs: [
      { question: 'Are weekend AC bookings available in Sholinganallur?', answer: 'Yes! We are open Saturdays and Sundays.' },
    ],
  },
  {
    id: 'omr',
    slug: 'omr',
    name: 'OMR (Old Mahabalipuram Road)',
    zone: 'OMR IT Corridor',
    postalCode: '600096',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in OMR | ChillFix AC Service',
    metaDescription: 'AC service across OMR Chennai (Perungudi to Navalur). Fast technician response for Split AC repair, jet wash & AMC.',
    heading: 'AC Service & Repair Across OMR',
    intro: 'ChillFix AC Service covers the OMR stretch from Perungudi to Thoraipakkam, Sholinganallur, and Navalur.',
    nearbyHubs: ['Perungudi', 'Thoraipakkam', 'Kandanchavadi', 'Navalur', 'Siruseri'],
    localFaqs: [
      { question: 'Which areas along OMR do you cover?', answer: 'We cover all areas along OMR including Perungudi, Thoraipakkam, Sholinganallur, and Navalur.' },
    ],
  },
  {
    id: 'velachery',
    slug: 'velachery',
    name: 'Velachery',
    zone: 'South-Central Chennai',
    postalCode: '600042',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Velachery | ChillFix AC Service',
    metaDescription: 'Doorstep AC service in Velachery, Chennai. Split & Window AC repair, foam jet wash, gas leak repair & installation near Phoenix Marketcity.',
    heading: 'AC Service & Repair in Velachery',
    intro: 'ChillFix AC Service delivers fast doorstep AC servicing, jet wash cleaning, PCB repair, and gas refilling across Velachery, Vijaya Nagar, Baby Nagar, and Taramani Road.',
    nearbyHubs: ['Vijaya Nagar', 'Baby Nagar', 'Phoenix Marketcity Zone', 'Taramani Road', 'Check Post Velachery'],
    localFaqs: [
      { question: 'Do you service ACs in Velachery apartments?', answer: 'Yes! We service residential apartments and individual houses across Velachery.' },
    ],
  },
  {
    id: 'porur',
    slug: 'porur',
    name: 'Porur',
    zone: 'West Chennai',
    postalCode: '600116',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Porur | ChillFix AC Service',
    metaDescription: 'Professional AC service in Porur, Chennai. Split AC repair, chemical jet wash, gas filling & installation near Ramachandra Hospital.',
    heading: 'AC Service & Repair in Porur',
    intro: 'ChillFix AC Service offers comprehensive AC repair and servicing across Porur, Mugalivakkam, Iyyapanthangal, and Mount-Poonamallee Road.',
    nearbyHubs: ['Porur Junction', 'Mugalivakkam', 'Iyyapanthangal', 'Ramachandra Zone', 'Mount-Poonamallee Road'],
    localFaqs: [
      { question: 'Do you offer emergency AC repair in Porur?', answer: 'Yes! Our technicians provide fast dispatch to Porur and surrounding residential colonies.' },
    ],
  },
  {
    id: 'guindy',
    slug: 'guindy',
    name: 'Guindy',
    zone: 'Central-South Chennai',
    postalCode: '600032',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Guindy | ChillFix AC Service',
    metaDescription: 'Trusted AC service in Guindy, Chennai. Commercial & residential AC repair, jet wash cleaning, gas filling near Industrial Estate & Kathipara.',
    heading: 'AC Service & Repair in Guindy',
    intro: 'ChillFix AC Service provides expert AC maintenance, PCB repair, and installation across Guindy Industrial Estate, Ekkatuthangal, and Race Course road.',
    nearbyHubs: ['Guindy Industrial Estate', 'Ekkatuthangal', 'Kathipara Zone', 'Race Course Road'],
    localFaqs: [
      { question: 'Do you offer commercial AC AMC in Guindy?', answer: 'Yes! We provide structured commercial AMC contracts for offices in Guindy Industrial Estate.' },
    ],
  },
  {
    id: 'anna-nagar',
    slug: 'anna-nagar',
    name: 'Anna Nagar',
    zone: 'North-West Chennai',
    postalCode: '600040',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Anna Nagar | ChillFix AC Service',
    metaDescription: 'Premium AC service in Anna Nagar, Chennai. Inverter AC repair, foam jet wash, gas filling & installation across East & West Anna Nagar.',
    heading: 'AC Service & Repair in Anna Nagar',
    intro: 'ChillFix AC Service delivers premium doorstep AC servicing, jet wash cleaning, and inverter PCB repair across Anna Nagar East, Anna Nagar West, Shenoy Nagar, and Shanthi Colony.',
    nearbyHubs: ['Shanthi Colony', 'Anna Nagar East', 'Anna Nagar West', 'Shenoy Nagar', 'Tower Park Zone'],
    localFaqs: [
      { question: 'Do you service Dual Inverter ACs in Anna Nagar?', answer: 'Yes! We specialize in Daikin, LG, Voltas, and Panasonic Dual Inverter AC repairs.' },
    ],
  },
  {
    id: 'adyar',
    slug: 'adyar',
    name: 'Adyar',
    zone: 'South Chennai',
    postalCode: '600020',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Adyar | ChillFix AC Service',
    metaDescription: 'Reliable AC service in Adyar, Chennai. Split & Window AC repair, foam jet wash cleaning, gas leak fix near Gandhi Nagar & LB Road.',
    heading: 'AC Service & Repair in Adyar',
    intro: 'ChillFix AC Service provides professional AC maintenance, jet wash cleaning, and gas leak brazing across Adyar, Gandhi Nagar, Kasturba Nagar, and Besant Nagar.',
    nearbyHubs: ['Gandhi Nagar', 'Kasturba Nagar', 'Besant Nagar', 'LB Road Adyar', 'Indira Nagar'],
    localFaqs: [
      { question: 'How quickly can I get AC service in Adyar?', answer: 'We dispatch local service technicians within 2 hours of booking in Adyar.' },
    ],
  },
  {
    id: 'mylapore',
    slug: 'mylapore',
    name: 'Mylapore',
    zone: 'Central-South Chennai',
    postalCode: '600004',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Mylapore | ChillFix AC Service',
    metaDescription: 'Expert AC service in Mylapore, Chennai. Split AC repair, jet wash, gas refilling & installation near Kapaleeshwarar Temple & Luz Church Road.',
    heading: 'AC Service & Repair in Mylapore',
    intro: 'ChillFix AC Service offers complete AC servicing, cooling troubleshooting, and installation across Mylapore, Luz Corner, Mandaveli, and Santhome.',
    nearbyHubs: ['Luz Corner', 'Mandaveli', 'Santhome', 'Oliver Road', 'RA Puram'],
    localFaqs: [
      { question: 'Do you offer Window AC repair in Mylapore?', answer: 'Yes! We repair and service Window and Split ACs across Mylapore.' },
    ],
  },
  {
    id: 'vadapalani',
    slug: 'vadapalani',
    name: 'Vadapalani',
    zone: 'Central-West Chennai',
    postalCode: '600026',
    responseTime: 'Fast Local Response',
    metaTitle: 'AC Service in Vadapalani | ChillFix AC Service',
    metaDescription: 'Fast AC service in Vadapalani, Chennai. Split AC repair, foam jet wash, gas leak repair & installation near SIMS Hospital & Forum Mall.',
    heading: 'AC Service & Repair in Vadapalani',
    intro: 'ChillFix AC Service provides prompt doorstep AC repair, jet wash servicing, and gas refilling across Vadapalani, Arcot Road, Saligramam, and Ashok Nagar.',
    nearbyHubs: ['Arcot Road', 'Saligramam', 'Ashok Nagar', 'Forum Mall Zone', 'SIMS Hospital Area'],
    localFaqs: [
      { question: 'Do you provide same-day AC gas filling in Vadapalani?', answer: 'Yes! Nitrogen leak testing and R32/R410A gas refilling are available same-day.' },
    ],
  },
];

// Helper to look up an area by slug (supports both 'perungalathur' and 'ac-service-perungalathur')
export function getAreaBySlug(slug: string): AreaLocation | undefined {
  const normalized = slug.toLowerCase().replace(/^ac-service-/, '');
  return AREA_LOCATIONS.find(
    (area) => area.id === normalized || area.slug === slug || area.slug === `ac-service-${normalized}` || area.id === slug,
  );
}
