import type { Service } from '@/types/service';

export const SERVICES: Service[] = [
  // --- AC Types ---
  {
    id: 'split-ac-service',
    slug: 'split-ac-service',
    name: 'Split AC Service',
    shortDescription: 'Complete installation, repair, and maintenance for split air conditioners.',
    description:
      'Our certified technicians provide comprehensive split AC services including installation, regular servicing, gas refilling, and component repairs. We handle all major brands with precision and care.',
    icon: 'AirVent',
    image: '/images/services/split-ac.jpg',
    category: 'residential',
    features: [
      'Professional wall mounting & pipe work',
      'Electrical connection & safety checks',
      'Performance testing & calibration',
      'Gas leak detection & refilling',
      'All major brand support',
    ],
    startingPrice: 299,
    duration: '1–2 Hours',
    warranty: '90 Days',
    popular: true,
  },
  {
    id: 'window-ac-service',
    slug: 'window-ac-service',
    name: 'Window AC Service',
    shortDescription: 'Expert window AC installation and repair with guaranteed performance.',
    description:
      'Specialized window AC services including installation, servicing, PCB repair, compressor replacement, and regular maintenance to keep your window unit running at peak efficiency.',
    icon: 'Square',
    image: '/images/services/window-ac.jpg',
    category: 'residential',
    features: [
      'Frame fitting & waterproofing',
      'Electrical safety compliance',
      'Cooling performance test',
      'Vibration & noise reduction',
      'Filter cleaning & replacement',
    ],
    startingPrice: 249,
    duration: '1–3 Hours',
    warranty: '90 Days',
    popular: false,
  },
  {
    id: 'cassette-ac-service',
    slug: 'cassette-ac-service',
    name: 'Cassette AC Service',
    shortDescription: 'Professional cassette AC installation & maintenance for offices and commercial spaces.',
    description:
      'Expert cassette AC installation and servicing for commercial and large residential spaces. Our technicians ensure proper ceiling integration, airflow optimization, and long-term performance.',
    icon: 'LayoutGrid',
    image: '/images/services/cassette-ac.jpg',
    category: 'commercial',
    features: [
      'Ceiling panel integration',
      'Multi-directional airflow setup',
      'Drain line installation',
      'Commercial load calculation',
      'BMS integration support',
    ],
    startingPrice: 499,
    duration: '2–4 Hours',
    warranty: '90 Days',
    popular: false,
  },
  {
    id: 'tower-ac-service',
    slug: 'tower-ac-service',
    name: 'Tower AC Service',
    shortDescription: 'Installation and maintenance for tower/floor-standing air conditioners.',
    description:
      'Complete tower AC services including positioning, electrical setup, duct work if required, and routine maintenance. Ideal for large halls, showrooms, and open spaces.',
    icon: 'Columns',
    image: '/images/services/tower-ac.jpg',
    category: 'commercial',
    features: [
      'Floor positioning & stabilization',
      'Airflow direction optimization',
      'Duct connection if applicable',
      'High-capacity cooling setup',
      'Noise reduction measures',
    ],
    startingPrice: 399,
    duration: '2–3 Hours',
    warranty: '90 Days',
    popular: false,
  },
  {
    id: 'commercial-ac-service',
    slug: 'commercial-ac-service',
    name: 'Commercial AC Service',
    shortDescription: 'End-to-end commercial HVAC solutions for offices, hospitals & restaurants.',
    description:
      'Comprehensive commercial AC solutions for multi-unit installations, central AC systems, and HVAC maintenance contracts. We serve offices, hospitals, schools, restaurants, and commercial buildings across Chennai.',
    icon: 'Building2',
    image: '/images/services/commercial-ac.jpg',
    category: 'commercial',
    features: [
      'Multi-unit system design',
      'Central AC installation',
      'Preventive maintenance contracts',
      'Emergency 24/7 support',
      'Energy efficiency consulting',
    ],
    startingPrice: 999,
    duration: 'Custom',
    warranty: '1 Year',
    popular: true,
  },
  // --- Service Types ---
  {
    id: 'ac-installation',
    slug: 'ac-installation',
    name: 'AC Installation',
    shortDescription: 'Fast, professional AC installation by certified technicians.',
    description:
      'Same-day AC installation service with proper pipe work, electrical connections, and testing. Our certified technicians ensure your AC is installed safely and efficiently the first time.',
    icon: 'Wrench',
    image: '/images/services/installation.jpg',
    category: 'installation',
    features: [
      'Same-day installation available',
      'All pipe & electrical work included',
      'Post-installation performance test',
      'Clean installation — no mess left behind',
      'Warranty on workmanship',
    ],
    startingPrice: 599,
    duration: '2–4 Hours',
    warranty: '90 Days',
    popular: true,
  },
  {
    id: 'ac-uninstallation',
    slug: 'ac-uninstallation',
    name: 'AC Uninstallation',
    shortDescription: 'Safe AC removal & relocation by experienced professionals.',
    description:
      'Professional AC uninstallation for relocation, unit replacement, or moving homes. We safely remove your AC, recover the refrigerant gas, and prepare the unit for reinstallation.',
    icon: 'ArrowDownToLine',
    image: '/images/services/uninstallation.jpg',
    category: 'installation',
    features: [
      'Gas recovery before uninstallation',
      'Safe pipe capping',
      'Wall damage minimization',
      'Unit storage guidance',
      'Reinstallation available',
    ],
    startingPrice: 349,
    duration: '1–2 Hours',
    warranty: '30 Days',
    popular: false,
  },
  {
    id: 'gas-filling',
    slug: 'gas-filling',
    name: 'Gas Filling (Refrigerant)',
    shortDescription: 'AC refrigerant gas refilling for R-22, R-32, R-410A & R-600A.',
    description:
      'Professional AC gas refilling service for all refrigerant types. We detect leaks first, repair them, then refill to exact manufacturer specifications for optimal cooling performance.',
    icon: 'Droplets',
    image: '/images/services/gas-filling.jpg',
    category: 'repair',
    features: [
      'Leak detection before refilling',
      'All refrigerant types supported',
      'Manufacturer-specified quantity',
      'Pressure testing after fill',
      'Eco-friendly gas handling',
    ],
    startingPrice: 799,
    duration: '1–2 Hours',
    warranty: '30 Days',
    popular: true,
  },
  {
    id: 'cooling-repair',
    slug: 'cooling-repair',
    name: 'Cooling Problem Repair',
    shortDescription: 'Fix "AC not cooling" problems — fast diagnosis & repair.',
    description:
      'Comprehensive cooling problem diagnosis and repair. We identify the root cause — whether it\'s low gas, dirty coils, faulty thermostat, or compressor issues — and fix it right the first time.',
    icon: 'Thermometer',
    image: '/images/services/cooling-repair.jpg',
    category: 'repair',
    features: [
      'Root cause diagnosis',
      'Thermostat testing & calibration',
      'Coil cleaning & inspection',
      'Compressor performance check',
      'Spare parts available',
    ],
    startingPrice: 449,
    duration: '1–3 Hours',
    warranty: '60 Days',
    popular: true,
  },
  {
    id: 'water-leakage-repair',
    slug: 'water-leakage-repair',
    name: 'Water Leakage Repair',
    shortDescription: 'Fix AC water leakage from indoor or outdoor units permanently.',
    description:
      'Expert diagnosis and repair of water leakage issues from AC units. Common causes include clogged drain pipes, frozen coils, and improper installation — all fixed by our technicians.',
    icon: 'Droplet',
    image: '/images/services/water-leakage.jpg',
    category: 'repair',
    features: [
      'Drain pipe cleaning & unclogging',
      'Condensate tray inspection',
      'Coil defrost procedure',
      'Pipe slope correction',
      'Seal & gasket replacement',
    ],
    startingPrice: 349,
    duration: '1–2 Hours',
    warranty: '60 Days',
    popular: false,
  },
  {
    id: 'pcb-repair',
    slug: 'pcb-repair',
    name: 'PCB Board Repair',
    shortDescription: 'Expert PCB / circuit board repair for all AC brands.',
    description:
      'Professional diagnosis and repair of AC printed circuit boards (PCB). Our technicians are equipped to repair and replace faulty PCBs for all major brands, saving you from expensive unit replacement.',
    icon: 'Circuit',
    image: '/images/services/pcb-repair.jpg',
    category: 'repair',
    features: [
      'Component-level diagnosis',
      'Capacitor & relay replacement',
      'Error code analysis',
      'OEM & compatible parts',
      'Board cleaning & protection',
    ],
    startingPrice: 599,
    duration: '2–4 Hours',
    warranty: '90 Days',
    popular: false,
  },
  {
    id: 'compressor-repair',
    slug: 'compressor-repair',
    name: 'Compressor Repair & Replacement',
    shortDescription: 'AC compressor repair and replacement at competitive prices.',
    description:
      'Expert compressor diagnosis, repair, and replacement. We carry OEM and compatible compressors for all major brands. Get your AC running again at a fraction of the cost of a new unit.',
    icon: 'Cog',
    image: '/images/services/compressor.jpg',
    category: 'repair',
    features: [
      'Compressor load testing',
      'Valve & bearing inspection',
      'Oil charging after replacement',
      'System flush & vacuum',
      'All brands stocked',
    ],
    startingPrice: 2999,
    duration: '3–6 Hours',
    warranty: '1 Year',
    popular: false,
  },
  {
    id: 'deep-cleaning',
    slug: 'deep-cleaning',
    name: 'AC Deep Cleaning',
    shortDescription: 'Thorough jet wash deep cleaning for better cooling & air quality.',
    description:
      'Professional deep cleaning service using high-pressure jet wash to remove dust, mold, and bacteria from indoor and outdoor units. Improves cooling efficiency by up to 30% and ensures healthier indoor air.',
    icon: 'Sparkles',
    image: '/images/services/deep-cleaning.jpg',
    category: 'maintenance',
    features: [
      'Foam jet wash for coils',
      'Filter cleaning & deodorization',
      'Drain pan sanitization',
      'Outdoor unit high-pressure wash',
      'Anti-bacterial treatment',
    ],
    startingPrice: 449,
    duration: '1–2 Hours',
    warranty: '30 Days',
    popular: true,
  },
  {
    id: 'annual-maintenance',
    slug: 'annual-maintenance',
    name: 'Annual Maintenance Contract (AMC)',
    shortDescription: 'Worry-free AC maintenance plans with priority service all year.',
    description:
      'Comprehensive Annual Maintenance Contracts (AMC) for residential and commercial AC units. Get scheduled servicing, priority emergency support, and exclusive discounts on repairs throughout the year.',
    icon: 'CalendarCheck',
    image: '/images/services/amc.jpg',
    category: 'maintenance',
    features: [
      '2–4 scheduled services/year',
      'Priority emergency response',
      'Free labour on covered repairs',
      'Discounts on spare parts',
      'Performance reports',
    ],
    startingPrice: 1499,
    duration: 'Annual',
    warranty: '1 Year',
    popular: true,
  },
];

export const SERVICE_CATEGORIES = [
  { id: 'all', label: 'All Services' },
  { id: 'residential', label: 'Residential' },
  { id: 'commercial', label: 'Commercial' },
  { id: 'installation', label: 'Installation' },
  { id: 'repair', label: 'Repair' },
  { id: 'maintenance', label: 'Maintenance' },
] as const;

export type ServiceCategory = (typeof SERVICE_CATEGORIES)[number]['id'];
