import type { Testimonial } from '@/types/testimonial';

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'testimonial-1',
    name: 'Rajesh Kumar',
    location: 'Anna Nagar, Chennai',
    rating: 5,
    text: 'Excellent service! The technician arrived within 90 minutes of my call. My 5-year-old Samsung split AC was not cooling at all. They diagnosed a gas leak, repaired the pipe, and refilled the gas. AC is now working perfectly. Very professional team.',
    service: 'Gas Filling & Leak Repair',
    date: '2025-06-15',
    verified: true,
    avatar: '/images/testimonials/avatar-1.jpg',
  },
  {
    id: 'testimonial-2',
    name: 'Priya Subramaniam',
    location: 'Adyar, Chennai',
    rating: 5,
    text: 'I have been using ChillFix for 3 years now. Their AMC plan is fantastic — 3 services a year, priority emergency support, and discounts on parts. My office ACs are always in top condition. Highly recommend their annual maintenance plan.',
    service: 'Annual Maintenance Contract',
    date: '2025-05-22',
    verified: true,
    avatar: '/images/testimonials/avatar-2.jpg',
  },
  {
    id: 'testimonial-3',
    name: 'Mohammed Farhan',
    location: 'T. Nagar, Chennai',
    rating: 5,
    text: 'Called at 11 PM because my AC compressor stopped working. ChillFix sent a technician within 2 hours. He diagnosed the capacitor was blown and replaced it on the spot. Saved me from a sleepless night. True emergency service!',
    service: 'Emergency Repair',
    date: '2025-07-03',
    verified: true,
    avatar: '/images/testimonials/avatar-3.jpg',
  },
  {
    id: 'testimonial-4',
    name: 'Sunitha Rajan',
    location: 'Velachery, Chennai',
    rating: 5,
    text: 'Got 3 new ACs installed for my new apartment. The team was punctual, clean, and very professional. They finished all 3 installations in 4 hours. No mess, no wall damage, and the ACs are cooling brilliantly. Great value for money.',
    service: 'AC Installation',
    date: '2025-04-10',
    verified: true,
    avatar: '/images/testimonials/avatar-4.jpg',
  },
  {
    id: 'testimonial-5',
    name: 'Dr. Arjun Menon',
    location: 'Nungambakkam, Chennai',
    rating: 5,
    text: 'We use ChillFix for all our clinic ACs. Their commercial service is top-notch. Regular maintenance keeps our ACs running without fail, which is critical for patient comfort. The technicians are always courteous and knowledgeable.',
    service: 'Commercial AC Service',
    date: '2025-03-18',
    verified: true,
    avatar: '/images/testimonials/avatar-5.jpg',
  },
  {
    id: 'testimonial-6',
    name: 'Kavitha Devi',
    location: 'Tambaram, Chennai',
    rating: 5,
    text: 'The deep cleaning service was amazing! My 3-year-old Daikin was smelling musty and not cooling well. After ChillFix did the jet wash deep cleaning, it cools 30% better and the air smells fresh. Should have done this earlier!',
    service: 'AC Deep Cleaning',
    date: '2025-06-28',
    verified: true,
    avatar: '/images/testimonials/avatar-6.jpg',
  },
  {
    id: 'testimonial-7',
    name: 'Vikram Raghunathan',
    location: 'OMR, Chennai',
    rating: 4,
    text: 'Good service overall. My window AC had a water leakage problem for months. ChillFix found the drain pipe was blocked and the tray was cracked. Fixed both issues in one visit. Fair pricing and honest assessment.',
    service: 'Water Leakage Repair',
    date: '2025-05-05',
    verified: true,
    avatar: '/images/testimonials/avatar-7.jpg',
  },
  {
    id: 'testimonial-8',
    name: 'Meenakshi Krishnan',
    location: 'Mylapore, Chennai',
    rating: 5,
    text: 'Booked through WhatsApp and the booking was confirmed in 10 minutes. Technician called before arriving. Very transparent — showed me all the issues on the PCB before replacing components. No unnecessary upselling. Very trustworthy.',
    service: 'PCB Repair',
    date: '2025-07-15',
    verified: true,
    avatar: '/images/testimonials/avatar-8.jpg',
  },
];
